spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:canteen_db}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:2007}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}

brevo.api.key=${BREVO_API_KEY}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:Root}
cloudinary.api-key=${CLOUDINARY_API_KEY:617241471577487}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:FPh_gycZ5efIiS_pSYuYSpPRabw}
google.client.id=673990758831-vt8vbpvbjuo4s5ia9mv71eesjk1gkuvc.apps.googleusercontent.com

